kind: Deployment
apiVersion: apps/v1
metadata:
  name: easy-wallet
  namespace: default
  selfLink: /apis/apps/v1/namespaces/default/deployments/easy-wallet
  uid: ef10780e-2a82-400e-87e1-9bd40420b6c9
  resourceVersion: '26611'
  generation: 6
  creationTimestamp: '2020-09-22T03:31:20Z'
  labels:
    app: easy-wallet
  annotations:
    deployment.kubernetes.io/revision: '5'
  managedFields:
    - manager: kubectl-create
      operation: Update
      apiVersion: apps/v1
      time: '2020-09-22T03:31:20Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:labels':
            .: {}
            'f:app': {}
        'f:spec':
          'f:progressDeadlineSeconds': {}
          'f:replicas': {}
          'f:revisionHistoryLimit': {}
          'f:selector':
            'f:matchLabels':
              .: {}
              'f:app': {}
          'f:strategy':
            'f:rollingUpdate':
              .: {}
              'f:maxSurge': {}
              'f:maxUnavailable': {}
            'f:type': {}
          'f:template':
            'f:metadata':
              'f:labels':
                .: {}
                'f:app': {}
            'f:spec':
              'f:containers':
                'k:{"name":"easy-wallet"}':
                  .: {}
                  'f:image': {}
                  'f:name': {}
                  'f:resources': {}
                  'f:terminationMessagePath': {}
                  'f:terminationMessagePolicy': {}
              'f:dnsPolicy': {}
              'f:restartPolicy': {}
              'f:schedulerName': {}
              'f:securityContext': {}
              'f:terminationGracePeriodSeconds': {}
    - manager: dashboard
      operation: Update
      apiVersion: apps/v1
      time: '2020-09-22T04:04:07Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:spec':
          'f:template':
            'f:spec':
              'f:containers':
                'k:{"name":"easy-wallet"}':
                  'f:imagePullPolicy': {}
    - manager: kubectl-rollout
      operation: Update
      apiVersion: apps/v1
      time: '2020-09-22T04:48:41Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:spec':
          'f:template':
            'f:metadata':
              'f:annotations':
                .: {}
                'f:kubectl.kubernetes.io/restartedAt': {}
    - manager: kube-controller-manager
      operation: Update
      apiVersion: apps/v1
      time: '2020-09-22T04:49:49Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            .: {}
            'f:deployment.kubernetes.io/revision': {}
        'f:status':
          'f:availableReplicas': {}
          'f:conditions':
            .: {}
            'k:{"type":"Available"}':
              .: {}
              'f:lastTransitionTime': {}
              'f:lastUpdateTime': {}
              'f:message': {}
              'f:reason': {}
              'f:status': {}
              'f:type': {}
            'k:{"type":"Progressing"}':
              .: {}
              'f:lastTransitionTime': {}
              'f:lastUpdateTime': {}
              'f:message': {}
              'f:reason': {}
              'f:status': {}
              'f:type': {}
          'f:observedGeneration': {}
          'f:readyReplicas': {}
          'f:replicas': {}
          'f:updatedReplicas': {}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: easy-wallet
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: easy-wallet
      annotations:
        kubectl.kubernetes.io/restartedAt: '2020-09-22T08:48:41+04:00'
    spec:
      containers:
        - name: easy-wallet
          image: 'docker.io/library/easy-wallet:latest'
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
status:
  observedGeneration: 6
  replicas: 2
  updatedReplicas: 2
  readyReplicas: 2
  availableReplicas: 2
  conditions:
    - type: Progressing
      status: 'True'
      lastUpdateTime: '2020-09-22T04:48:42Z'
      lastTransitionTime: '2020-09-22T04:04:07Z'
      reason: NewReplicaSetAvailable
      message: ReplicaSet "easy-wallet-ff6b9c56d" has successfully progressed.
    - type: Available
      status: 'True'
      lastUpdateTime: '2020-09-22T04:49:49Z'
      lastTransitionTime: '2020-09-22T04:49:49Z'
      reason: MinimumReplicasAvailable
      message: Deployment has minimum availability.
